<?php
$data=array(

'title'                         => $title,                                                
'first_name'                    => $firstName,                                               
'middleName'                    => $middleName,
'surname'                       => $surname, 
'last_updated'                  => $created,                                

'staff_profile.sex'                 => $sex,                             
'staff_profile.dOb'                 => $dOb,                             
'staff_profile.placeOfBirth'        => $placeOfBirth,                                                  
'staff_profile.marritalStatus'      => $marritalStatus,                                                  
'staff_profile.staffCat'            => strtolower($staffCat),                                            
'staff_profile.picName'             => $picName,//$picName,                                        
'staff_profile.cv'                  => $cv,//$picName,                                        
'staff_profile.biography'           => $biography,//$picName,                                        
'staff_profile.awards'              => [],//$picName,                                        
'staff_profile.professional_qual'   => [],//$picName,                                        
'staff_profile.staffIDNo'           => $staffIDNo,                                        
'staff_profile.nationality'         => $nationality,                                        

'contact.LGAofOrigin'               => $LGAofOrigin,                                        
'contact.stateOfOrigin'             => $stateOfOrigin,  
'contact.geoPoliticalZone'          => $geoPoliticalZone,                                        
'contact.wardOfOrigin'              => $wardOfOrigin,                                       
'contact.stateOfRes'                => $stateOfRes,                    
'contact.LGAOfRes'                  => $LGAOfRes,                            
'contact.PAddress'                  => $PAddress,               
'contact.Caddress'                  => $Caddress,                                 
'contact.phone'                     => $phone,               
'contact.email'                     => $email,
'spouse.spouseFirstName'           => $spouseFirstName,                                        
'spouse.spouseMiddleName'          => $spouseMiddleName,                                        
'spouse.spouseLastName'            => $spouseLastName,                    
'spouse.spouseOccupation'          => $spouseOccupation,                            
'spouse.spousePlaceOfWork'         => $spousePlaceOfWork,               
'spouse.spouseResedentialAddress'  => $spouseResedentialAddress,                                 
'spouse.spousePhone'               => $spousePhone,               

'children.child1.childName'           => $childName1,                                        
'children.child1.date_of_Birth'       => $childBirth1,                                        
'children.child1.childSex'            => $childSex1,                    
   
'children.child2.childName'           => $childName2,                                        
'children.child2.date_of_Birth'       => $childBirth2,                                        
'children.child2.childSex'            => $childSex2,                    
    
'children.child3.childName'           => $childName3,                                        
'children.child3.date_of_Birth'       => $childBirth3,                                        
'children.child3.childSex'            => $childSex3,                    
    
'children.child4.childName'           => $childName4,                                        
'children.child4.date_of_Birth'       => $childBirth4,                                        
'children.child4.childSex'            => $childSex4,                    
    

    'next_of_kin.NokFirstName'        => $NokFirstName,                                        
    'next_of_kin.NokMiddleName'       => $NokMiddleName,                                        
    'next_of_kin.NokLastName'         => $NokLastName,
    'next_of_kin.relationship'        => $relationship,         
    'next_of_kin.NokSex'              => $NokSex,                            
    'next_of_kin.NokContackAdd'       => $NokContackAdd,               
    'next_of_kin.NokAddress'          => $NokAddress,               
    'next_of_kin.NokEmail'            => $NokEmail,                                 
    'next_of_kin.NokPhoneNumber'      => $NokPhoneNumber,               
 //'registry'=>[
    'registry.PFileNo'               => $PFileNo,                                        
    'registry.faculty'               => strtolower($faculty),                                        
    'registry.dept'                  => strtolower($dept),                    
    'registry.unit'                  => strtolower($unit),                            
    'registry.designation'           => strtolower($designation),               
    'registry.designationOnFirstApp' => strtolower($designationOnFirstApp),               
    'registry.postion'               => $postion,                                 
    'registry.areaOfSpecialization'  => $areaOfSpecialization,
    'registry.acadQuatnsWithDate'    => $acadQuatnsWithDate,                                        
    'registry.certification'         => [$certification],                                        
    'registry.PHYCHAL'               => $PHYCHAL,                                        
    'registry.union'                 => $union,                    
    'registry.date_employed'         => $date_employed,                            
    'registry.date_confirmed'        => $date_confirmed,               
    'registry.staff_Status'          => $staff_Status,                                 
    'registry.dateOfAssumptionOfDuty'=> $dateOfAssumptionOfDuty,
    'registry.cadreOn1stApp'         => strtolower($cadreOn1stApp),                                        
    'registry.levelOn1stApp'         => $levelOn1stApp,                                        
    'registry.stepOn1stApp'          => $stepOn1stApp,                    
    'registry.currentLevel'          => $currentLevel,                            
    'registry.currentStep'           => $currentStep,               
    'registry.currentCadre'          => $currentCadre,                                 
    'registry.incStep'               => $incStep,
    'registry.dateOfRetirementByAge' => $dateOfRetirementByAge,                                        
    'registry.dateOfRetirementByEmpl'=> $dateOfRetirementByEmpl,                                        
    'registry.dateOfRetirement'      => $dateOfRetirement,                    
    'registry.exitDates'             => $exitDates,                    
    'registry.dateOfResignation'     => $dateOfResignation,                            
    'registry.employmentHist'        => $employmentHist,               
    //'registry.leaveStatus'           => $leaveStatus,               
    //'registry.leaveType'             => $leaveType,                                 
    'registry.leaveMonth'            => $leaveMonth,                                 
    'registry.leaveDay'              => $leaveDay,                                 
    //'registry.leaveEffectDate'       => $leaveEffectDate,
    //'registry.leaveResumeDate'       => $leaveResumeDate,
    //'registry.leaveNoDays'           => $leaveNoDays,                                        
    //'registry.leaveExpireDate'       => $leaveExpireDate,                                        
    'registry.groupCadre'            => strtolower($groupCadre),                    
    'registry.staffType'             => strtolower($staffType),                    
    'registry.initial'               => $initial,                            
    'registry.CONTSRTDATE'           => $CONTSRTDATE,               
    'registry.CONTEXPDATE'           => $CONTEXPDATE,                                 
    'registry.NoOfRenewedContract'   => $NoOfRenewedContract,               
    'registry.promotion.lastPromDate'   => $lastPromDate,               
    'registry.promotion.staff_under_review.date_and_grade_on_first_appointment'   => $date_employed.' grade level '.$levelOn1stApp.' step '.$stepOn1stApp.'.',               
    'registry.promotion.staff_under_review.appointment_confirmation.appointmentStatus'   => $appointmentStatus,               
    'registry.promotion.staff_under_review.appointment_confirmation.date_confirmed'   => $date_confirmed,               
 //],
    'bursary.bursaryNo'             => $bursaryNo,                                        
    'bursary.IPPIS_NO'              => $IPPIS_NO,                                        
    'bursary.SalaryCategory'        => strtolower($SalaryCategory),                    
    'bursary.bankName'              => $bankName,                            
    'bursary.accountNumber'         => $accountNumber,               
    'bursary.PFANAme'               => $PFANAme,                                 
    'bursary.PENSION_PIN'           => $PENSION_PIN,               
             
            
);